### ISSUE TITLE
$VERSION specified twice (causing redeclaration warnings)

### ISSUE THREAD

**Issue by eserte** [Csson/p5-Map-Metro-Amsterdam#1] opened 2015-01-20 19:29 UTC
See https://metacpan.org/source/CSSON/Map-Metro-Plugin-Map-Amsterdam-0.1100/lib/Map/Metro/Plugin/Map/Amsterdam/Lines.pm#L3
It seems that also other maps are affected - here's a list of warnings when running the Map-Metro-Plugin-Map-Berlin test suite:

```
"our" variable $VERSION redeclared at /opt/perl-5.20.1/lib/site_perl/5.20.1/Map/Metro/Plugin/Map/Athens/Lines.pm line 3.
"our" variable $VERSION redeclared at /opt/perl-5.20.1/lib/site_perl/5.20.1/Map/Metro/Plugin/Map/Bilbao/Lines.pm line 3.
"our" variable $VERSION redeclared at /opt/perl-5.20.1/lib/site_perl/5.20.1/Map/Metro/Plugin/Map/Brescia/Lines.pm line 3.
"our" variable $VERSION redeclared at /opt/perl-5.20.1/lib/site_perl/5.20.1/Map/Metro/Plugin/Map/Amsterdam/Lines.pm line 3.
```

**Comment by Csson** [comment] 2015-01-20 23:59
Hi,

That was not good. The problem is in the Dist::Zilla plugin that creates the Lines.pm file. In some of the maps $VERSION is doubled and in some it's not set at all. I'm not sure why my own tests haven't caught this.. I'll update this when I have a fix in place.

**Comment by Csson** [comment] 2015-01-21 15:45
I have fixed Dist::Zilla::Plugin::MapMetro::MakeLinesPod so it creates .pod files instead. No $VERSION is inserted. All maps should be fixed before the end of January.

**Closed as completed by Csson** 2015-01-21 15:45 UTC
